spring:  profiles:    active:    - chaos-monkeychaos:  monkey:    enabled: true    watcher:      service: true      component: false      controller: false      rest-controller: false      repository: falseserver:  port: 8090

management.health.circuitbreakers.enabled: truemanagement.endpoint.chaosmonkey.enabled: truemanagement.endpoint.chaosmonkeyjmx.enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
        health:
          show-details: always          
  
resilience4j.circuitbreaker:    instances:        chaosmonkey:            registerHealthIndicator: true            slidingWindowSize: 10            permittedNumberOfCallsInHalfOpenState: 2            slidingWindowType: COUNT_BASED            minimumNumberOfCalls: 3            waitDurationInOpenState: 20s            failureRateThreshold: 50            eventConsumerBufferSize: 10            record-exceptions:            - org.springframework.web.client.ResourceAccessException            - java.net.ConnectException            - java.lang.RuntimeException        getEmploye:
            registerHealthIndicator: true
            slidingWindowSize: 10
            permittedNumberOfCallsInHalfOpenState: 5
            slidingWindowType: COUNT_BASED
            minimumNumberOfCalls: 4
            waitDurationInOpenState: 20s
            failureRateThreshold: 50
            eventConsumerBufferSize: 10            record-exceptions:            - org.springframework.web.client.ResourceAccessException            - java.net.ConnectException            - java.lang.RuntimeException        
resilience4j:
  retry:    instances:
        getEmployetretry:
          max-retry-attempts: 3
          wait-duration:  1000            
          
                 
